// Writes src/lib/xterm-assets.ts: xterm.js, its WebGL renderer and its
// stylesheet as strings, for the terminal WebView to load inline — no
// network, no bundler step in the page. Run after upgrading @xterm/xterm or
// @xterm/addon-webgl: `npm run embed-xterm`.

import { readFileSync, writeFileSync } from 'node:fs';

const js = readFileSync(new URL('../node_modules/@xterm/xterm/lib/xterm.js', import.meta.url), 'utf8');
const webgl = readFileSync(new URL('../node_modules/@xterm/addon-webgl/lib/addon-webgl.js', import.meta.url), 'utf8');
const css = readFileSync(new URL('../node_modules/@xterm/xterm/css/xterm.css', import.meta.url), 'utf8');
const version = JSON.parse(
  readFileSync(new URL('../node_modules/@xterm/xterm/package.json', import.meta.url), 'utf8'),
).version;
const webglVersion = JSON.parse(
  readFileSync(new URL('../node_modules/@xterm/addon-webgl/package.json', import.meta.url), 'utf8'),
).version;
// Both packages are MIT, whose notice has to travel with every copy.
const license = (name) =>
  readFileSync(new URL(`../node_modules/${name}/LICENSE`, import.meta.url), 'utf8')
    .trim()
    .split('\n')
    .map((line) => (line ? `// ${line}` : '//'))
    .join('\n');

writeFileSync(
  new URL('../src/lib/xterm-assets.ts', import.meta.url),
  `// Generated by scripts/embed-xterm.mjs from @xterm/xterm ${version} and\n` +
    `// @xterm/addon-webgl ${webglVersion}. Do not edit.\n` +
    `//\n// @xterm/xterm:\n//\n${license('@xterm/xterm')}\n` +
    `//\n// @xterm/addon-webgl:\n//\n${license('@xterm/addon-webgl')}\n` +
    `export const XTERM_JS = ${JSON.stringify(js)};\n` +
    `export const XTERM_WEBGL_JS = ${JSON.stringify(webgl)};\n` +
    `export const XTERM_CSS = ${JSON.stringify(css)};\n`,
);
console.log(
  `embedded @xterm/xterm ${version} and @xterm/addon-webgl ${webglVersion}: ${js.length + webgl.length + css.length} bytes`,
);
